export const FETCH_CONTEXT = "FETCH_CONTEXT";

export const RUN_EXPERIMENT = "RUN_EXPERIMENT";
export const EXPERIMENT_DONE = "EXPERIMENT_DONE";

export const ADD_EXPERIMENT = "ADD_EXPERIMENT";
export const UPDATE_EXPERIMENT = "UPDATE_EXPERIMENT";
export const DELETE_EXPERIMENT = "DELETE_EXPERIMENT";

export const ADDING_DATASET = "ADDING_DATASET";
export const ADDED_DATASET = "ADDED_DATASET";
export const DATASET_ERROR = "DATASET_ERROR";
