export const FETCH_CONTEXT = "FETCH_CONTEXT";
export const SERVER_UNRESPONSIVE = "SERVER_UNRESPONSIVE";

export const OVERWRITE_EXPERIMENT = "OVERWRITE_EXPERIMENT";
export const ADD_EXPERIMENTS = "ADD_EXPERIMENTS";
export const UPDATE_EXPERIMENT = "UPDATE_EXPERIMENT";
export const DELETE_EXPERIMENT = "DELETE_EXPERIMENT";

export const ADDING_DATASET = "ADDING_DATASET";
export const ADDED_DATASET = "ADDED_DATASET";
export const DATASET_ERROR = "DATASET_ERROR";
