#!/bin/bash

echo ""
echo "Starting deployment"
echo ""

# Ensure needed versions
cd ~/code
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
if [ ! -d "venv" ]; then
 virtualenv venv -p python3
fi
source venv/bin/activate

echo ""
echo "Checking out current version"
git --work-tree=/home/deploy/code/ --git-dir=/home/deploy/git/ checkout -f
chmod a+x scripts/remove-data.sh

echo ""
echo "Installing dependencies"
echo ""
cd ~/code
chmod a+x scripts/install.sh
source scripts/install.sh

echo ""
echo "Starting in production mode"
cd ~/code
chmod a+x scripts/prod-start.sh
source scripts/prod-start.sh

echo ""
echo "Deployment finished"
lsof -i:5000
echo ""
