#!/bin/bash

echo ""
echo "Starting deployment"
echo ""
echo "Killing server"
killall python
echo ""
echo "Checking out current version"
git --work-tree=/home/deploy/code/ --git-dir=/home/deploy/git/ checkout -f
cd ~/code
echo ""
echo "Installing dependencies"
echo ""
pip install -r requirements.txt
cd client && npm install
echo ""
echo "Starting in production mode"
cd ..
docker-compose up -d
cd client
npm run build
cd ..
nohup python app.py >> info.log 2>> error.log &
echo ""
echo "Deployment finished"
echo ""
